### ISSUE TITLE
Add this to allow gulp to run with NodeJS >= 12

### ISSUE THREAD

**Issue by Nicocchi** [pokemon-essentials/pokemon-essentials#4]
I do not know if this project is still active, but I wanted to give some insight on some things.

I came across some errors trying to build the project with gulp. My version of Node, and probably many others, are greater than the version compatible with `gulp 3.9`. Here is a solution that doesn't require user's to use a version of Node under 10 or rewrite your existing gulp code for `gulp 4.3`.

Add a file named: `npm-shrinkwrap.json` in the root directory with `package.json` with the following contents:
`{
    "dependencies": {
      "graceful-fs": {
          "version": "4.2.2"
       }
    }
  }`

Then run `npm i` to install the depends and it'll automatically update the shrinkwrap file. Now the build command will run smoothly on modern versions of Node.

**Comment by crynxmartinez** [comment]
Did it work?

**Comment by Nicocchi** [comment]
It did. This just takes the graceful-fs dependency and upgrades it to a version that is compatible with Node 12. My initial error was:

```
$npm run build

> pokemon-essentials@0.0.1 build /home/nicocchi/Documents/Development/Projects/pokemon-essentials
> gulp dev-build

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/nicocchi/Documents/Development/Projects/pokemon-essentials/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/nicocchi/Documents/Development/Projects/pokemon-essentials/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/nicocchi/Documents/Development/Projects/pokemon-essentials/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pokemon-essentials@0.0.1 build: `gulp dev-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-essentials@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nicocchi/.npm/_logs/2020-02-29T00_25_24_296Z-debug.log
```

Which is due to versions of Gulp under 4 not compatible with Node 12.

**Comment by Souvikns** [comment]
I also getting this error, and I am using node 20 and it is not working
